from contextlib import contextmanager

import frappe
from frappe import _, DoesNotExistError
from erpnext.accounts.doctype.pos_invoice_merge_log.pos_invoice_merge_log import (
    consolidate_pos_invoices,
)


@contextmanager
def _negative_stock_close_shift_guard():
    """Best-effort relaxation of ERPNext's bin-level negative stock check.

    The earlier iteration of this guard tried to monkey-patch every
    batch-stock validator in ``SerialandBatchBundle`` and
    ``stock_ledger.is_negative_stock_allowed`` so close-shift could
    swallow stale-batch issues silently. That played whack-a-mole with
    ERPNext's validation surface (a new throw site appeared every
    iteration) and the right answer per the cashier was to **stop
    bypassing validators and surface the offending invoices instead**.

    What we keep here is just ``frappe.flags.allow_negative_stock = True``
    so the bin-level path that *does* honour the flag (
    ``stock_ledger.make_sl_entries`` accepting an ``allow_negative_stock``
    kwarg, callers that fall back to the flag for legacy reasons) gets
    the relaxed behaviour. Anything stricter — batch-level validators,
    POSAwesome's own batch quantity check, etc. — is intentionally
    allowed to throw. ``submit_printed_invoices`` now catches those per
    invoice and returns them as ``blocking_errors`` for the frontend to
    surface, giving the cashier an explicit "delete and retry" choice
    instead of an opaque close-shift failure.

    The flag is restored in ``finally`` so it can't leak to subsequent
    requests on the same worker.
    """

    previous_flag = getattr(frappe.flags, "allow_negative_stock", False)
    frappe.flags.allow_negative_stock = True
    try:
        yield
    finally:
        frappe.flags.allow_negative_stock = previous_flag


# Back-compat alias for any external import that grabbed the old name.
_negative_stock_consolidation_guard = _negative_stock_close_shift_guard

def _set_closing_entry_invoices(closing_shift_doc):
    """Set `pos_closing_entry` on linked invoices."""
    for d in closing_shift_doc.pos_transactions:
        invoice = d.get("sales_invoice") or d.get("pos_invoice")
        if not invoice:
            continue
        doctype = "Sales Invoice" if d.get("sales_invoice") else "POS Invoice"
        if frappe.db.has_column(doctype, "pos_closing_entry"):
            frappe.db.set_value(doctype, invoice, "pos_closing_entry", closing_shift_doc.name)

def _clear_closing_entry_invoices(closing_shift_doc):
    """Clear closing shift links, cancel merge logs and cancel consolidated sales invoices."""
    consolidated_sales_invoices = set()
    for d in closing_shift_doc.pos_transactions:
        pos_invoice = d.get("pos_invoice")
        sales_invoice = d.get("sales_invoice")
        if pos_invoice:
            if frappe.db.has_column("POS Invoice", "pos_closing_entry"):
                frappe.db.set_value("POS Invoice", pos_invoice, "pos_closing_entry", None)

            merge_logs = frappe.get_all(
                "POS Invoice Merge Log",
                filters={"pos_invoice": pos_invoice},
                pluck="name",
            )
            for log in merge_logs:
                log_doc = frappe.get_doc("POS Invoice Merge Log", log)
                for field in (
                    "consolidated_invoice",
                    "consolidated_credit_note",
                ):
                    si = log_doc.get(field)
                    if si:
                        consolidated_sales_invoices.add(si)
                if log_doc.docstatus == 1:
                    log_doc.cancel()
                frappe.delete_doc("POS Invoice Merge Log", log_doc.name, force=1)

            if frappe.db.has_column("POS Invoice", "consolidated_invoice"):
                frappe.db.set_value("POS Invoice", pos_invoice, "consolidated_invoice", None)

            if frappe.db.has_column("POS Invoice", "status"):
                pos_doc = frappe.get_doc("POS Invoice", pos_invoice)
                pos_doc.set_status(update=True)

        if sales_invoice:
            if frappe.db.has_column("Sales Invoice", "pos_closing_entry"):
                frappe.db.set_value("Sales Invoice", sales_invoice, "pos_closing_entry", None)
            if _is_consolidated_sales_invoice(sales_invoice):
                consolidated_sales_invoices.add(sales_invoice)

    for si in consolidated_sales_invoices:
        if frappe.db.exists("Sales Invoice", si):
            si_doc = frappe.get_doc("Sales Invoice", si)
            if si_doc.docstatus == 1:
                si_doc.cancel()

def _is_consolidated_sales_invoice(sales_invoice):
    """Return True if the Sales Invoice was generated by consolidating POS Invoices."""

    if not sales_invoice:
        return False

    if frappe.db.exists("POS Invoice Merge Log", {"consolidated_invoice": sales_invoice}):
        return True

    return bool(frappe.db.exists("POS Invoice Merge Log", {"consolidated_credit_note": sales_invoice}))

def _resolve_pos_invoice_doctype(pos_profile):
    """POS Invoice or Sales Invoice depending on profile config."""

    use_pos_invoice = frappe.db.get_value(
        "POS Profile",
        pos_profile,
        "create_pos_invoice_instead_of_sales_invoice",
    )
    return "POS Invoice" if use_pos_invoice else "Sales Invoice"


def delete_draft_invoices(pos_opening_shift, pos_profile):
    if frappe.get_value("POS Profile", pos_profile, "posa_allow_delete"):
        doctype = _resolve_pos_invoice_doctype(pos_profile)
        data = frappe.db.sql(
            f"""
        select
            name
        from
            `tab{doctype}`
        where
            docstatus = 0 and posa_is_printed = 0 and posa_pos_opening_shift = %s
        """,
            (pos_opening_shift),
            as_dict=1,
        )

        for invoice in data:
            frappe.delete_doc(doctype, invoice.name, force=1)


@frappe.whitelist()
def get_open_draft_invoices(pos_opening_shift, pos_profile):
    """List unsubmitted (draft) invoices in the opening shift.

    Used by the close-shift dialog so the cashier can review + clean up
    drafts *before* triggering the close (which would otherwise leave the
    drafts hanging or auto-delete them silently when ``posa_allow_delete``
    is on).

    Two buckets are returned:
      - ``unprinted`` — drafts the cashier never printed; safe to delete
        because no goods left the counter and no money was collected on
        them.
      - ``printed``  — drafts that hit the printer (``posa_is_printed=1``)
        but never reached docstatus=1; the cashier likely handed over goods
        and collected payment for these. Listed so the cashier can see
        what's about to be auto-submitted on close — NOT offered for
        deletion via the cleanup endpoint (see ``delete_open_draft_invoices``).
    """

    if not pos_opening_shift or not pos_profile:
        return {"unprinted": [], "printed": [], "doctype": None}

    doctype = _resolve_pos_invoice_doctype(pos_profile)
    rows = frappe.get_all(
        doctype,
        filters={
            "posa_pos_opening_shift": pos_opening_shift,
            "docstatus": 0,
        },
        fields=["name", "customer", "grand_total", "posting_date", "posa_is_printed"],
        order_by="posting_date desc, modified desc",
    )

    unprinted = []
    printed = []
    for row in rows:
        bucket = printed if row.get("posa_is_printed") else unprinted
        bucket.append(
            {
                "name": row.get("name"),
                "customer": row.get("customer") or "",
                "grand_total": row.get("grand_total") or 0,
                "posting_date": row.get("posting_date"),
            }
        )

    return {
        "unprinted": unprinted,
        "printed": printed,
        "doctype": doctype,
    }


@frappe.whitelist()
def delete_open_draft_invoices(pos_opening_shift, pos_profile, names=None):
    """Delete draft invoices in the shift.

    Two modes:

    - **No ``names`` list** (default) — wipes every ``posa_is_printed=0``
      draft in the shift. Safe because no goods left the counter on
      those.
    - **Explicit ``names`` list** — deletes exactly those invoice IDs,
      regardless of ``posa_is_printed``. Used by the close-shift
      "blocked by draft submit" recovery flow when the cashier needs to
      remove a printed-but-unsubmittable draft to unblock close.
      Caller is expected to gate this with explicit user confirmation
      since deleting a printed draft erases an audit trail entry.

    Returns ``{"deleted": [names], "skipped": [names]}`` so the UI can
    show what was actually cleaned up vs. what stayed for the cashier
    to handle.
    """

    if not pos_opening_shift or not pos_profile:
        return {"deleted": [], "skipped": []}

    doctype = _resolve_pos_invoice_doctype(pos_profile)

    # Normalise `names` — Frappe whitelisted methods receive JSON-serialized
    # lists as strings, so accept both list and JSON-string forms.
    if isinstance(names, str):
        try:
            names = frappe.parse_json(names)
        except Exception:
            names = [names]

    if names:
        # Targeted delete — confirm each invoice belongs to this shift to
        # prevent the endpoint from being abused to wipe arbitrary docs.
        names = [n for n in names if n]
        if not names:
            return {"deleted": [], "skipped": []}
        rows = frappe.get_all(
            doctype,
            filters={
                "posa_pos_opening_shift": pos_opening_shift,
                "docstatus": 0,
                "name": ["in", names],
            },
            pluck="name",
        )
    else:
        rows = frappe.get_all(
            doctype,
            filters={
                "posa_pos_opening_shift": pos_opening_shift,
                "docstatus": 0,
                "posa_is_printed": 0,
            },
            pluck="name",
        )

    deleted = []
    skipped = []
    for invoice_name in rows:
        try:
            frappe.delete_doc(doctype, invoice_name, force=1)
            deleted.append(invoice_name)
        except Exception as error:
            skipped.append(invoice_name)
            frappe.log_error(
                title="POS Close-Shift Draft Cleanup Skipped",
                message=_("Could not delete draft {0}: {1}").format(
                    invoice_name, frappe.get_traceback() or str(error)
                ),
            )

    return {"deleted": deleted, "skipped": skipped}

def _get_cancelled_return_against(invoice_doc, doctype):
    if not invoice_doc.get("is_return"):
        return None

    return_against = invoice_doc.get("return_against")
    if not return_against:
        return None

    if frappe.db.get_value(doctype, return_against, "docstatus") == 2:
        return return_against

    return None

def submit_printed_invoices(pos_opening_shift, doctype):
    """Auto-submit printed-but-unsubmitted invoices for close-shift.

    Returns a dict with two buckets so callers can react instead of
    propagating an opaque exception::

        {
            "skipped":         [<rows whose `return_against` is cancelled>],
            "blocking_errors": [<rows whose .submit() raised>],
        }

    On the *first* submit failure we abort the loop and roll the
    transaction back. That keeps the close-shift atomic (no half-
    submitted shift state) and lets the cashier review the offending
    invoice via the new "Close-shift blocked" dialog: they can delete
    the blocking draft and retry, or cancel the close. See
    ``creation.make_closing_shift_from_opening`` for the response
    shape and ``CloseShiftBlockingErrorsDialog.vue`` for the UI.
    """

    skipped_invoices = []
    blocking_errors = []
    invoices_list = frappe.get_all(
        doctype,
        filters={
            "posa_pos_opening_shift": pos_opening_shift,
            "docstatus": 0,
            "posa_is_printed": 1,
        },
    )

    with _negative_stock_close_shift_guard():
        for invoice in invoices_list:
            invoice_doc = frappe.get_doc(doctype, invoice.name)
            cancelled_return_against = _get_cancelled_return_against(invoice_doc, doctype)
            if cancelled_return_against:
                skipped_invoices.append(
                    frappe._dict(
                        {
                            "invoice": invoice_doc.name,
                            "doctype": doctype,
                            "return_against": cancelled_return_against,
                        }
                    )
                )
                frappe.log_error(
                    title="POS Closing Shift Skipped Invalid Return Draft",
                    message=_(
                        "Skipped printed draft invoice {0} during close shift because Return Against {1} is cancelled."
                    ).format(invoice_doc.name, cancelled_return_against),
                )
                continue

            try:
                invoice_doc.submit()
            except Exception as error:
                # Abort the close-shift submit chain on first failure so
                # the cashier doesn't end up with a half-submitted shift
                # (rolling back undoes any earlier successful submits in
                # this loop, which is what we want — the close-shift
                # response will let them delete the blocking draft and
                # retry, at which point all printed drafts get re-tried
                # cleanly).
                frappe.db.rollback()
                blocking_errors.append(
                    frappe._dict(
                        {
                            "invoice": invoice_doc.name,
                            "doctype": doctype,
                            "customer": invoice_doc.get("customer") or "",
                            "grand_total": flt(invoice_doc.get("grand_total") or 0),
                            "message": frappe.utils.cstr(error)[:2000],
                        }
                    )
                )
                frappe.log_error(
                    title="POS Closing Shift Blocked By Draft Submit",
                    message=_(
                        "Submit of printed draft invoice {0} failed during close shift: {1}"
                    ).format(invoice_doc.name, frappe.get_traceback() or str(error)),
                )
                break

    return {"skipped": skipped_invoices, "blocking_errors": blocking_errors}


def _normalize_submit_printed_result(result):
    """Backwards-compat shim for callers that handed us the legacy list."""

    if isinstance(result, dict):
        return result
    if result is None:
        return {"skipped": [], "blocking_errors": []}
    # Legacy: a list of skipped rows.
    return {"skipped": list(result or []), "blocking_errors": []}

def consolidate_closing_shift_invoices(closing_shift_doc):
    if frappe.db.get_value(
        "POS Profile",
        closing_shift_doc.pos_profile,
        "create_pos_invoice_instead_of_sales_invoice",
    ):
        pos_invoices = []
        for d in closing_shift_doc.pos_transactions:
            invoice_details = frappe._dict(
                frappe.db.get_value(
                    "POS Invoice",
                    d.pos_invoice,
                    [
                        "name as pos_invoice",
                        "customer",
                        "is_return",
                        "return_against",
                        "currency",
                    ],
                    as_dict=True,
                )
            )
            if invoice_details:
                pos_invoices.append(invoice_details)

        if pos_invoices:
            invoices_by_currency = {}
            for invoice in pos_invoices:
                invoices_by_currency.setdefault(invoice.currency, []).append(invoice)

            # Suppress ERPNext's per-batch negative-stock validator only for
            # the consolidation reposting — see _negative_stock_close_shift_guard
            # for the full rationale.
            with _negative_stock_close_shift_guard():
                for invoices in invoices_by_currency.values():
                    consolidate_pos_invoices(pos_invoices=invoices)
